/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoadmapIndexImport } from './routes/roadmap/index'
import { Route as DownloadIndexImport } from './routes/download/index'
import { Route as DiscordIndexImport } from './routes/discord/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as GithubNameImport } from './routes/github/$name'
import { Route as DownloadPrivateImport } from './routes/download/private'
import { Route as DeepLinkDeeplinkImport } from './routes/deep-link/$deep_link'
import { Route as PluginsProvidersIndexImport } from './routes/plugins/providers/index'
import { Route as AuthSignUpIndexImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexImport } from './routes/auth/sign-in/index'
import { Route as AdminRoadmapIndexImport } from './routes/admin/roadmap/index'
import { Route as AdminAnalyticsIndexImport } from './routes/admin/analytics/index'
import { Route as PluginsProvidersAddIndexImport } from './routes/plugins/providers/add/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RoadmapIndexRoute = RoadmapIndexImport.update({
  id: '/roadmap/',
  path: '/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)

const DownloadIndexRoute = DownloadIndexImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordIndexRoute = DiscordIndexRouteImport.update({
  id: '/discord/',
  path: '/discord/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubNameRoute = GithubNameRouteImport.update({
  id: '/github/$name',
  path: '/github/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadPrivateRoute = DownloadPrivateRouteImport.update({
  id: '/download/private',
  path: '/download/private',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepLinkDeep_linkRoute = DeepLinkDeep_linkRouteImport.update({
  id: '/deep-link/$deep_link',
  path: '/deep-link/$deep_link',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsProvidersIndexRoute = PluginsProvidersIndexRouteImport.update({
  id: '/plugins/providers/',
  path: '/plugins/providers/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpIndexRoute = AuthSignUpIndexImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInIndexRoute = AuthSignInIndexImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoadmapIndexRoute = AdminRoadmapIndexImport.update({
  id: '/admin/roadmap/',
  path: '/admin/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/admin/analytics/',
  path: '/admin/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)

const PluginsProvidersAddIndexRoute = PluginsProvidersAddIndexImport.update({
  id: '/plugins/providers/add/',
  path: '/plugins/providers/add/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/deep-link/$deep_link': {
      id: '/deep-link/$deep_link'
      path: '/deep-link/$deep_link'
      fullPath: '/deep-link/$deep_link'
      preLoaderRoute: typeof DeepLinkDeeplinkImport
      parentRoute: typeof rootRoute
    }
    '/download/private': {
      id: '/download/private'
      path: '/download/private'
      fullPath: '/download/private'
      preLoaderRoute: typeof DownloadPrivateImport
      parentRoute: typeof rootRoute
    }
    '/github/$name': {
      id: '/github/$name'
      path: '/github/$name'
      fullPath: '/github/$name'
      preLoaderRoute: typeof GithubNameImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/discord/': {
      id: '/discord/'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordIndexImport
      parentRoute: typeof rootRoute
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadIndexImport
      parentRoute: typeof rootRoute
    }
    '/roadmap/': {
      id: '/roadmap/'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/roadmap/': {
      id: '/admin/roadmap/'
      path: '/admin/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof AdminRoadmapIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/providers/': {
      id: '/plugins/providers/'
      path: '/plugins/providers'
      fullPath: '/plugins/providers'
      preLoaderRoute: typeof PluginsProvidersIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/providers/add/': {
      id: '/plugins/providers/add/'
      path: '/plugins/providers/add'
      fullPath: '/plugins/providers/add'
      preLoaderRoute: typeof PluginsProvidersAddIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/deep-link/$deep_link': typeof DeepLinkDeep_linkRoute
  '/download/private': typeof DownloadPrivateRoute
  '/github/$name': typeof GithubNameRoute
  '/admin': typeof AdminIndexRoute
  '/discord': typeof DiscordIndexRoute
  '/download': typeof DownloadIndexRoute
  '/roadmap': typeof RoadmapIndexRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/roadmap': typeof AdminRoadmapIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/plugins/providers': typeof PluginsProvidersIndexRoute
  '/plugins/providers/add': typeof PluginsProvidersAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/deep-link/$deep_link': typeof DeepLinkDeep_linkRoute
  '/download/private': typeof DownloadPrivateRoute
  '/github/$name': typeof GithubNameRoute
  '/admin': typeof AdminIndexRoute
  '/discord': typeof DiscordIndexRoute
  '/download': typeof DownloadIndexRoute
  '/roadmap': typeof RoadmapIndexRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/roadmap': typeof AdminRoadmapIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/plugins/providers': typeof PluginsProvidersIndexRoute
  '/plugins/providers/add': typeof PluginsProvidersAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/deep-link/$deep_link': typeof DeepLinkDeep_linkRoute
  '/download/private': typeof DownloadPrivateRoute
  '/github/$name': typeof GithubNameRoute
  '/admin/': typeof AdminIndexRoute
  '/discord/': typeof DiscordIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/roadmap/': typeof AdminRoadmapIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/plugins/providers/': typeof PluginsProvidersIndexRoute
  '/plugins/providers/add/': typeof PluginsProvidersAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deep-link/$deep_link'
    | '/download/private'
    | '/github/$name'
    | '/admin'
    | '/discord'
    | '/download'
    | '/roadmap'
    | '/admin/analytics'
    | '/admin/roadmap'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/plugins/providers'
    | '/plugins/providers/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deep-link/$deep_link'
    | '/download/private'
    | '/github/$name'
    | '/admin'
    | '/discord'
    | '/download'
    | '/roadmap'
    | '/admin/analytics'
    | '/admin/roadmap'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/plugins/providers'
    | '/plugins/providers/add'
  id:
    | '__root__'
    | '/'
    | '/deep-link/$deep_link'
    | '/download/private'
    | '/github/$name'
    | '/admin/'
    | '/discord/'
    | '/download/'
    | '/roadmap/'
    | '/admin/analytics/'
    | '/admin/roadmap/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/plugins/providers/'
    | '/plugins/providers/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DeepLinkDeep_linkRoute: typeof DeepLinkDeep_linkRoute
  DownloadPrivateRoute: typeof DownloadPrivateRoute
  GithubNameRoute: typeof GithubNameRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DiscordIndexRoute: typeof DiscordIndexRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
  RoadmapIndexRoute: typeof RoadmapIndexRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminRoadmapIndexRoute: typeof AdminRoadmapIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
  PluginsProvidersIndexRoute: typeof PluginsProvidersIndexRoute
  PluginsProvidersAddIndexRoute: typeof PluginsProvidersAddIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/': {
      id: '/roadmap/'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord/': {
      id: '/discord/'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/$name': {
      id: '/github/$name'
      path: '/github/$name'
      fullPath: '/github/$name'
      preLoaderRoute: typeof GithubNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/private': {
      id: '/download/private'
      path: '/download/private'
      fullPath: '/download/private'
      preLoaderRoute: typeof DownloadPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-link/$deep_link': {
      id: '/deep-link/$deep_link'
      path: '/deep-link/$deep_link'
      fullPath: '/deep-link/$deep_link'
      preLoaderRoute: typeof DeepLinkDeep_linkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/providers/': {
      id: '/plugins/providers/'
      path: '/plugins/providers'
      fullPath: '/plugins/providers'
      preLoaderRoute: typeof PluginsProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roadmap/': {
      id: '/admin/roadmap/'
      path: '/admin/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof AdminRoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/providers/add/': {
      id: '/plugins/providers/add/'
      path: '/plugins/providers/add'
      fullPath: '/plugins/providers/add'
      preLoaderRoute: typeof PluginsProvidersAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DeepLinkDeep_linkRoute: DeepLinkDeep_linkRoute,
  DownloadPrivateRoute: DownloadPrivateRoute,
  GithubNameRoute: GithubNameRoute,
  AdminIndexRoute: AdminIndexRoute,
  DiscordIndexRoute: DiscordIndexRoute,
  DownloadIndexRoute: DownloadIndexRoute,
  RoadmapIndexRoute: RoadmapIndexRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminRoadmapIndexRoute: AdminRoadmapIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
  PluginsProvidersIndexRoute: PluginsProvidersIndexRoute,
  PluginsProvidersAddIndexRoute: PluginsProvidersAddIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/deep-link/$deep_link",
        "/download/private",
        "/github/$name",
        "/admin/",
        "/discord/",
        "/download/",
        "/roadmap/",
        "/admin/analytics/",
        "/admin/roadmap/",
        "/auth/sign-in/",
        "/auth/sign-up/",
        "/plugins/providers/",
        "/plugins/providers/add/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/deep-link/$deep_link": {
      "filePath": "deep-link/$deep_link.tsx"
    },
    "/download/private": {
      "filePath": "download/private.tsx"
    },
    "/github/$name": {
      "filePath": "github/$name.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/discord/": {
      "filePath": "discord/index.tsx"
    },
    "/download/": {
      "filePath": "download/index.tsx"
    },
    "/roadmap/": {
      "filePath": "roadmap/index.tsx"
    },
    "/admin/analytics/": {
      "filePath": "admin/analytics/index.tsx"
    },
    "/admin/roadmap/": {
      "filePath": "admin/roadmap/index.tsx"
    },
    "/auth/sign-in/": {
      "filePath": "auth/sign-in/index.tsx"
    },
    "/auth/sign-up/": {
      "filePath": "auth/sign-up/index.tsx"
    },
    "/plugins/providers/": {
      "filePath": "plugins/providers/index.tsx"
    },
    "/plugins/providers/add/": {
      "filePath": "plugins/providers/add/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
